-- QUERY 1
-- List all Customers
SELECT *
FROM SALES.CUSTOMER;

-- QUERY 2
-- List all customers where company name ending in N
SELECT *
FROM SALES.CUSTOMER
WHERE COMPANYNAME LIKE '%N';

-- QUERY 3
-- List of all customers who live in Berlin or London
SELECT *
FROM SALES.CUSTOMER C
JOIN PERSON.ADDRESS A ON C.ADDRESSID = A.ADDRESSID
WHERE A.CITY IN ('Berlin', 'London');

-- QUERY 4
-- List of all customers who live in UK or USA
SELECT *
FROM SALES.CUSTOMER C
JOIN PERSON.ADDRESS A ON C.ADDRESSID = A.ADDRESSID
JOIN PERSON.COUNTRYREGION CR ON A.COUNTRYREGIONCODE = CR.COUNTRYREGIONCODE
WHERE CR.NAME IN ('United Kingdom', 'United States');

-- QUERY 5
-- List of all products sorted by product name
SELECT *
FROM PRODUCTION.PRODUCT
ORDER BY NAME;

-- QUERY 6
-- List of all products where product name starts with an A
SELECT *
FROM PRODUCTION.PRODUCT
WHERE NAME LIKE 'A%';

-- QUERY 7
-- List of customers who ever placed an order
SELECT DISTINCT C.*
FROM SALES.CUSTOMER C
JOIN SALES.SALESORDERHEADER SOH ON C.CUSTOMERID = SOH.CUSTOMERID;

-- QUERY 8
-- List of customers who live in London and have bought a Chai
SELECT DISTINCT C.*
FROM SALES.CUSTOMER C
JOIN PERSON.ADDRESS A ON C.ADDRESSID = A.ADDRESSID
JOIN SALES.SALESORDERHEADER SOH ON C.CUSTOMERID = SOH.CUSTOMERID
JOIN SALES.SALESORDERDETAIL SOD ON SOH.SALESORDERID = SOD.SALESORDERID
JOIN PRODUCTION.PRODUCT P ON SOD.PRODUCTID = P.PRODUCTID
WHERE A.CITY = 'London' AND P.NAME = 'Chai';

-- QUERY 9
-- List of customers who ever placed an order
SELECT DISTINCT C.*
FROM SALES.CUSTOMER C
JOIN SALES.SALESORDERHEADER SOH ON C.CUSTOMERID <> SOH.CUSTOMERID;

-- QUERY 10
-- List of customers who ordered tofu
SELECT DISTINCT C.*
FROM SALES.CUSTOMER C
JOIN SALES.SALESORDERHEADER SOH ON C.CUSTOMERID = SOH.CUSTOMERID
JOIN SALES.SALESORDERDETAIL SOD ON SOH.SALESORDERID = SOD.SALESORDERID
JOIN PRODUCTION.PRODUCT P ON SOD.PRODUCTID = P.PRODUCTID
WHERE P.NAME = 'Tofu';

-- QUERY 11
-- Details of first order of the system
SELECT TOP 1 *
FROM SALES.SALESORDERHEADER
ORDER BY ORDERDATE;

-- QUERY 12
-- Find the details of most expensive order date
SELECT TOP 1 SOH.*, SUM(SOD.UNITPRICE * SOD.ORDERQTY) AS TOTALPRICE
FROM SALES.SALESORDERHEADER SOH
JOIN SALES.SALESORDERDETAIL SOD ON SOH.SALESORDERID = SOD.SALESORDERID
GROUP BY SOH.SALESORDERID, SOH.ORDERDATE, SOH.CUSTOMERID, SOH.SUBTOTAL, SOH.TAXAMT, SOH.FREIGHT, SOH.TOTALDUE, SOH.SHIPDATE
ORDER BY TOTALPRICE DESC;

-- QUERY 13
-- For each order get the OrderID and Average quantity of items in that order
SELECT SALESORDERID, AVG(ORDERQTY) AS AVERAGEQUANTITY
FROM SALES.SALESORDERDETAIL
GROUP BY SALESORDERID;

-- QUERY 14
-- For each order get the OrderID, minimum quantity and maximum quantity of that order
SELECT SALESORDERID, MIN(ORDERQTY) AS MINQUANTITY, MAX(ORDERQTY) AS MAXQUANTITY
FROM SALES.SALESORDERDETAIL
GROUP BY SALESORDERID;

-- QUERY 15
-- Get a list of all managers and the total number of employees that report to them
SELECT MGR.BUSINESSENTITYID AS MANAGERID, COUNT(EMP.BUSINESSENTITYID) AS EMPLOYEES_COUNT
FROM HUMANRESOURCES.EMPLOYEE EMP
JOIN HUMANRESOURCES.EMPLOYEE MGR ON EMP.MANAGERID = MGR.BUSINESSENTITYID
GROUP BY MGR.BUSINESSENTITYID;

-- QUERY 16
-- Get the OrderID and the total quantity of each order that has a total quantity greater than 300
SELECT SALESORDERID, SUM(ORDERQTY) AS TOTALQUANTITY
FROM SALES.SALESORDERDETAIL
GROUP BY SALESORDERID
HAVING SUM(ORDERQTY) > 300;

-- QUERY 17
-- List of all orders placed on or after 1996/12/31
SELECT *
FROM SALES.SALESORDERHEADER
WHERE ORDERDATE >= '1996-12-31';

-- QUERY 18
-- List of all orders shipped to Canada
SELECT SOH.*
FROM SALES.SALESORDERHEADER SOH
JOIN PERSON.ADDRESS A ON SOH.SHIPTOADDRESSID = A.ADDRESSID
JOIN PERSON.COUNTRYREGION CR ON A.COUNTRYREGIONCODE = CR.COUNTRYREGIONCODE
WHERE CR.NAME = 'Canada';

-- QUERY 19
-- List of all orders with order total greater than 200
SELECT *
FROM SALES.SALESORDERHEADER
WHERE TOTALDUE > 200;

-- QUERY 20
-- List of countries and sales made in each country
SELECT CR.NAME AS COUNTRY, SUM(SOH.TOTALDUE) AS TOTALSALES
FROM SALES.SALESORDERHEADER SOH
JOIN PERSON.ADDRESS A ON SOH.SHIPTOADDRESSID = A.ADDRESSID
JOIN PERSON.COUNTRYREGION CR ON A.COUNTRYREGIONCODE = CR.COUNTRYREGIONCODE
GROUP BY CR.NAME;

-- QUERY 21
-- List of Customer ContactName and number of orders they placed
SELECT C.CONTACTNAME, COUNT(SOH.SALESORDERID) AS NUMBEROFORDERS
FROM SALES.CUSTOMER C
JOIN SALES.SALESORDERHEADER SOH ON C.CUSTOMERID = SOH.CUSTOMERID
GROUP BY C.CONTACTNAME;

-- QUERY 22
-- List of customer contact names who have placed more than 3 orders
SELECT C.CONTACTNAME
FROM SALES.CUSTOMER C
JOIN SALES.SALESORDERHEADER SOH ON C.CUSTOMERID = SOH.CUSTOMERID
GROUP BY C.CONTACTNAME
HAVING COUNT(SOH.SALESORDERID) > 3;

-- QUERY 23
-- List of discontinued products which were ordered between 1/1/1997 and 1/1/1998
SELECT DISTINCT P.NAME AS PRODUCTNAME
FROM PRODUCTION.PRODUCT P
JOIN SALES.SALESORDERDETAIL SOD ON P.PRODUCTID = SOD.PRODUCTID
JOIN SALES.SALESORDERHEADER SOH ON SOD.SALESORDERID = SOH.SALESORDERID
WHERE P.DISCONTINUEDDATE IS NOT NULL
AND SOH.ORDERDATE BETWEEN '1997-01-01' AND '1998-01-01';

-- QUERY 24
-- List of Employee firstname, lastname and supervisor firstname and lastname
SELECT E1.FIRSTNAME AS EMPLOYEEFIRSTNAME, E1.LASTNAME AS EMPLOYEELASTNAME,
       E2.FIRSTNAME AS SUPERVISORFIRSTNAME, E2.LASTNAME AS SUPERVISORLASTNAME
FROM HUMANRESOURCES.EMPLOYEE E1
LEFT JOIN HUMANRESOURCES.EMPLOYEE E2 ON E1.MANAGERID = E2.BUSINESSENTITYID;

-- QUERY 25
-- List of employee id and the total sales conducted by an employee
SELECT SOH.SALESPERSONID AS EMPLOYEEID, SUM(SOH.TOTALDUE) AS TOTALSALES
FROM SALES.SALESORDERHEADER SOH
GROUP BY SOH.SALESPERSONID;

-- QUERY 26
-- List of employees whose firstname contain character a
SELECT FIRSTNAME, LASTNAME
FROM HUMANRESOURCES.EMPLOYEE
WHERE FIRSTNAME LIKE '%A%';

-- QUERY 27
-- List of managers who have more than 4 people reporting to them
SELECT MGR.BUSINESSENTITYID AS MANAGERID, COUNT(EMP.BUSINESSENTITYID) AS EMPLOYEES_COUNT
FROM HUMANRESOURCES.EMPLOYEE EMP
JOIN HUMANRESOURCES.EMPLOYEE MGR ON EMP.MANAGERID = MGR.BUSINESSENTITYID
GROUP BY MGR.BUSINESSENTITYID
HAVING COUNT(EMP.BUSINESSENTITYID) > 4;

-- QUERY 28
-- List of Orders and Product Names
SELECT SOH.SALESORDERID, P.NAME AS PRODUCTNAME
FROM SALES.SALESORDERHEADER SOH
JOIN SALES.SALESORDERDETAIL SOD ON SOH.SALESORDERID = SOD.SALESORDERID
JOIN PRODUCTION.PRODUCT P ON SOD.PRODUCTID = P.PRODUCTID;

-- QUERY 29
-- List of orders placed by the best customer
-- Assuming "best customer" is the one with the highest total sales
SELECT TOP 1 WITH TIES SOH.*
FROM SALES.SALESORDERHEADER SOH
JOIN SALES.CUSTOMER C ON SOH.CUSTOMERID = C.CUSTOMERID
GROUP BY SOH.SALESORDERID, SOH.ORDERDATE, SOH.CUSTOMERID, SOH.SUBTOTAL, SOH.TAXAMT, SOH.FREIGHT, SOH.TOTALDUE, SOH.SHIPDATE
ORDER BY SUM(SOH.TOTALDUE) OVER(PARTITION BY SOH.CUSTOMERID) DESC;

-- QUERY 30
-- List of orders placed by customers who do not have a FAX number
SELECT SOH.*
FROM SALES.SALESORDERHEADER SOH
JOIN SALES.CUSTOMER C ON SOH.CUSTOMERID = C.CUSTOMERID
WHERE C.FAX IS NULL;

-- QUERY 31
-- List of product codes where the product Tofu was shipped
SELECT DISTINCT SOD.PRODUCTID
FROM SALES.SALESORDERDETAIL SOD
JOIN PRODUCTION.PRODUCT P ON SOD.PRODUCTID = P.PRODUCTID
WHERE P.NAME = 'Tofu';

-- QUERY 32
-- List of product names that were shipped to France
SELECT DISTINCT P.NAME AS PRODUCTNAME
FROM SALES.SALESORDERDETAIL SOD
JOIN PRODUCTION.PRODUCT P ON SOD.PRODUCTID = P.PRODUCTID
JOIN SALES.SALESORDERHEADER SOH ON SOD.SALESORDERID = SOH.SALESORDERID
JOIN PERSON.ADDRESS A ON SOH.SHIPTOADDRESSID = A.ADDRESSID
JOIN PERSON.COUNTRYREGION CR ON A.COUNTRYREGIONCODE = CR.COUNTRYREGIONCODE
WHERE CR.NAME = 'France';

-- QUERY 33
-- List of ProductNames and Categories for the supplier 'Specialty Biscuits, Ltd'
SELECT P.NAME AS PRODUCTNAME, PC.NAME AS CATEGORYNAME
FROM PRODUCTION.PRODUCT P
JOIN PRODUCTION.PRODUCTCATEGORY PC ON P.PRODUCTCATEGORYID = PC.PRODUCTCATEGORYID
JOIN PURCHASING.PRODUCTVENDOR PV ON P.PRODUCTID = PV.PRODUCTID
JOIN PURCHASING.VENDOR V ON PV.VENDORID = V.VENDORID
WHERE V.NAME = 'Specialty Biscuits, Ltd';

-- QUERY 34
-- List of products that were never ordered
SELECT P.NAME
FROM PRODUCTION.PRODUCT P
LEFT JOIN SALES.SALESORDERDETAIL SOD ON P.PRODUCTID = SOD.PRODUCTID
WHERE SOD.SALESORDERID IS NULL;

-- QUERY 35
-- List of products where units in stock is less than 10 and units on order are 0
SELECT P.NAME
FROM PRODUCTION.PRODUCT P
WHERE P.UNITSINSTOCK < 10 AND P.UNITSONORDER = 0;

-- QUERY 36
-- List of top 10 countries by sales
SELECT TOP 10 CR.NAME AS COUNTRY, SUM(SOH.TOTALDUE) AS TOTALSALES
FROM SALES.SALESORDERHEADER SOH
JOIN PERSON.ADDRESS A ON SOH.SHIPTOADDRESSID = A.ADDRESSID
JOIN PERSON.COUNTRYREGION CR ON A.COUNTRYREGIONCODE = CR.COUNTRYREGIONCODE
GROUP BY CR.NAME
ORDER BY TOTALSALES DESC;

-- QUERY 37
-- Number of orders each employee has taken for customers with CustomerIDs between A and AO
SELECT E.BUSINESSENTITYID AS EMPLOYEEID, COUNT(SOH.SALESORDERID) AS NUMBEROFORDERS
FROM SALES.SALESORDERHEADER SOH
JOIN HUMANRESOURCES.EMPLOYEE E ON SOH.SALESPERSONID = E.BUSINESSENTITYID
JOIN SALES.CUSTOMER C ON SOH.CUSTOMERID = C.CUSTOMERID
WHERE C.CUSTOMERID BETWEEN 'A' AND 'AO'
GROUP BY E.BUSINESSENTITYID;

-- QUERY 38
-- Orderdate of most expensive order
SELECT TOP 1 SOH.ORDERDATE
FROM SALES.SALESORDERHEADER SOH
JOIN SALES.SALESORDERDETAIL SOD ON SOH.SALESORDERID = SOD.SALESORDERID
GROUP BY SOH.ORDERDATE, SOH.SALESORDERID
ORDER BY SUM(SOD.UNITPRICE * SOD.ORDERQTY) DESC;

-- QUERY 39
-- Product name and total revenue from that product
SELECT P.NAME AS PRODUCTNAME, SUM(SOD.UNITPRICE * SOD.ORDERQTY) AS TOTALREVENUE
FROM SALES.SALESORDERDETAIL SOD
JOIN PRODUCTION.PRODUCT P ON SOD.PRODUCTID = P.PRODUCTID
GROUP BY P.NAME;

-- QUERY 40
-- SupplierID and number of products offered
SELECT PV.VENDORID AS SUPPLIERID, COUNT(PV.PRODUCTID) AS NUMBEROFPRODUCTS
FROM PURCHASING.PRODUCTVENDOR PV
GROUP BY PV.VENDORID;

-- QUERY 41
-- Top ten customers based on their business
SELECT TOP 10 C.CUSTOMERID, SUM(SOH.TOTALDUE) AS TOTALBUSINESS
FROM SALES.SALESORDERHEADER SOH
JOIN SALES.CUSTOMER C ON SOH.CUSTOMERID = C.CUSTOMERID
GROUP BY C.CUSTOMERID
ORDER BY TOTALBUSINESS DESC;

-- QUERY 42
-- What is the total revenue of the company
SELECT SUM(SOH.TOTALDUE) AS TOTALREVENUE
FROM SALES.SALESORDERHEADER SOH;

